services:
  app:
    image: app
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////usr/src/app/data/test.db
      - JWT_TOKEN
      - JWT_ALGORITHM
      - ACCESS_TOKEN_EXPIRE_MINUTES
    volumes:
      - app_data:/usr/src/app/data


  telegram_bot:
    image: telegram_bot
    build:
      context: .
      dockerfile: ./telegram_bot/Dockerfile
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////app/data/test.db
      - BOT_TOKEN
      - API_BASE_URL=http://app:8000
    depends_on:
      - app
    volumes:
      - app_data:/app/data


  web_portal:
    image: web_portal
    build:
      context: ./web_portal
    ports:
      - "8001:8001"
    depends_on:
      - app
    volumes:
      - app_data:/usr/src/app/data


volumes:
  app_data:
