services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dbname"]
      interval: 5s
      timeout: 5s
      retries: 5


  app:
    image: app
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/dbname
      - JWT_TOKEN
      - JWT_ALGORITHM
      - ACCESS_TOKEN_EXPIRE_MINUTES
    volumes:
      - app_data:/usr/src/app/data

  telegram_bot:
    image: telegram_bot
    build:
      context: .
      dockerfile: ./telegram_bot/Dockerfile
    environment:
      - BOT_TOKEN
      - API_BASE_URL=http://app:8000
    depends_on:
      - app

  web_portal:
    image: web_portal
    build:
      context: ./web_portal
    ports:
      - "8001:80"
    depends_on:
      - app
    environment:
      - API_BASE_URL=http://app:8000

volumes:
  postgres_data:
  app_data:
