"""add cascade delete

Revision ID: 9a22a568c68e
Revises: de1f8431ff1e
Create Date: 2025-11-17 00:58:53.211913

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '9a22a568c68e'
down_revision: Union[str, Sequence[str], None] = 'de1f8431ff1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
