"""update qr, access log

Revision ID: f959ab94e5f2
Revises: e763091322d9
Create Date: 2025-10-30 01:24:19.388591

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f959ab94e5f2'
down_revision: Union[str, Sequence[str], None] = 'e763091322d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_qr_codes_code'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_id'), table_name='qr_codes')
    op.drop_table('qr_codes')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_access_logs_id'), table_name='access_logs')
    op.drop_table('access_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'access_logs',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.Column('organization_id', sa.INTEGER(), nullable=False),
        sa.Column('qr_code_id', sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ['organization_id'],
            ['organizations.id'],
        ),
        sa.ForeignKeyConstraint(
            ['qr_code_id'],
            ['qr_codes.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_access_logs_id'), 'access_logs', ['id'], unique=False
    )
    op.create_table(
        'users',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('telegram_id', sa.INTEGER(), nullable=False),
        sa.Column('name', sa.VARCHAR(length=100), nullable=False),
        sa.Column('organization_id', sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ['organization_id'],
            ['organizations.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=1
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table(
        'qr_codes',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('code', sa.VARCHAR(length=255), nullable=False),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.Column('organization_id', sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ['organization_id'],
            ['organizations.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_qr_codes_id'), 'qr_codes', ['id'], unique=False)
    op.create_index(
        op.f('ix_qr_codes_code'), 'qr_codes', ['code'], unique=False
    )
    op.create_table(
        'organizations',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('name', sa.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_index(
        op.f('ix_organizations_id'), 'organizations', ['id'], unique=False
    )
    # ### end Alembic commands ###
